name: Deploy to Local Minikube

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag'
        required: true
        default: 'v1'

jobs:
  build-and-deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Minikube Docker daemon
        run: eval $(minikube docker-env)

      - name: Build Docker Image
        run: docker build -t sample-app:${{ inputs.image_tag }} ./GitHub_Actions/Local_minikube_deployment/sample-app

      - name: Deploy to Minikube
        run: |
          kubectl apply -f ./GitHub_Actions/Local_minikube_deployment/sample-app/k8s/deployment.yaml
          kubectl apply -f ./GitHub_Actions/Local_minikube_deployment/sample-app/k8s/service.yaml
