name: Deploy to Local Minikube

on:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'Docker Image Tag'
        required: true
        default: 'v1'

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Your local machine will act as runner
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Minikube Docker daemon
        run: |
          eval $(minikube docker-env)

      - name: Build Docker Image
        run: |
          docker build -t sample-app:${{ github.event.inputs.image_tag }} ./GitHub_Actions/sample-app

      - name: Update image tag in deployment.yaml
        run: |
          sed "s|sample-app:latest|sample-app:${{ github.event.inputs.image_tag }}|" k8s/deployment.yaml > k8s/deployment-updated.yaml

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment-updated.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout status deployment/sample-app
